### ISSUE TITLE
[Python] Change in CMC APIs

### ISSUE THREAD

**Issue by buinguyentung** [buinguyentung/volume24bot#10]
As I know, CMC plans to change its APIs from December 2018.
Please investigate the difference and update the python code if needed.

**Comment by hodinhtan** [comment]
https://coinmarketcap.com/api/

> The Public API will be migrating to the new, more powerful Professional API on December 4th, 2018. Please update your application to use the free tier of the Professional API before then. 

I am ready for v2 coinmarketcap api. the estimate time to migrate pretty short.

**Comment by buinguyentung** [comment]
https://pro.coinmarketcap.com/pricing
=> Basic:free:
5 market data endpoints 
10K call credits /mo
No historical data
Personal use
